# Generated by Django 4.2.3 on 2025-04-12 18:20

import uuid

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to=files.models.file_upload_path)),
                ("file_path", models.CharField(editable=False, max_length=255)),
                (
                    "file_hash",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("size", models.BigIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("ref_count", models.PositiveIntegerField(default=1)),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("file_type", models.CharField(blank=True, max_length=20, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_deleted", "uploaded_at"],
                        name="files_file_is_dele_d3fdaa_idx",
                    ),
                    models.Index(
                        fields=["file_hash"], name="files_file_file_ha_868749_idx"
                    ),
                ],
            },
        ),
    ]
