# Generated by Django 4.2.21 on 2025-05-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="file_path",
        ),
        migrations.AlterField(
            model_name="file",
            name="file_type",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="file",
            name="original_filename",
            field=models.CharField(max_length=255),
        ),
    ]
